#!/usr/bin/env bash

set -euo pipefail

: ${REPO:="$(pwd)"}
: ${CC:=clang}
CFLAGS="-Wall -Wextra -Werror -Wnull-dereference -Wformat=2
-Wshadow -Wsign-conversion -Wfloat-equal -Wswitch-enum -Wmissing-prototypes
-Wdeprecated-declarations -fsanitize=undefined -fsanitize=thread -std=c11 -g"
LDFLAGS="-lpthread"

cc() {
	echo "CC	$@"
	$CC $CFLAGS $LDFLAGS $@
}

execute() {
	echo "EXEC	$@"
	$@
	echo "exit code $?"
}

bundle() {
	awk 'BEGIN { print "/**" } { print "* " $0 } END { print "**/" }' < "$REPO"/LICENSE
	echo
	echo "#ifndef EVENTLOOP_H_INCLUDE"
	echo "#define EVENTLOOP_H_INCLUDE"
	cat "$REPO"/src/eventloop.h | grep -v '#include "'
	echo
	echo "#ifdef EVENTLOOP_THREADPOOL"
	echo
	echo "#define THREADPOOL_IMPLEMENTATION"
	cat $THREADPOOL_INCLUDE/threadpool.h | grep -v '#include "'
	echo
	echo "#define MPSC_IMPLEMENTATION"
	cat $MPSC_INCLUDE/mpsc.h | grep -v '#include "'
	echo
	cat "$REPO"/src/impl/tpool.h | grep -v '#include "'
	cat "$REPO"/src/impl/tpool.c | grep -v '#include "'
	echo
	echo "#endif /* EVENTLOOP_THREADPOOL */"
	echo
	echo "#endif /* EVENTLOOP_H_INCLUDE */"
}

case "${1:-bundle}" in
	bundle|eventloop.h)
		bundle > eventloop.h
		;;

	test)
		cc -I. test.c -o test
		execute timeout 3s ./test
		;;

	bench)
		cc -I. -O3 bench.c -o bench
		execute ./bench
		;;

	compile_flags.txt)
		echo $CFLAGS -Isrc/ -I$THREADPOOL_INCLUDE -I$MPSC_INCLUDE \
			| tr ' ' '\n' > compile_flags.txt
		;;

	*)
		echo "unknown command: '${1-}'" >&2
		exit 1
		;;
esac
